---
deployment:
  tasks:
    - export DEPLOYPATH=/home/oshizdab/onestop/
    - /bin/cp -v onestop/requirements.txt $DEPLOYPATH
    - /bin/cp -R onestop/static/ $DEPLOYPATH
    - /bin/cp -R onestop/templates/ $DEPLOYPATH
    - /bin/cp onestop/onestop/practice.py $DEPLOYPATH/onestop/practice.py
    - /bin/cp onestop/onestop/urls.py $DEPLOYPATH/onestop/urls.py
    # Blog
    - /bin/cp -R onestop/blog/static/ $DEPLOYPATH/blog
    - /bin/cp -R onestop/blog/templates/ $DEPLOYPATH/blog
    - /bin/cp -R onestop/blog/tests/ $DEPLOYPATH/blog/
    - /bin/cp onestop/blog/admin.py $DEPLOYPATH/blog/admin.py
    - /bin/cp onestop/blog/forms.py $DEPLOYPATH/blog/forms.py
    - /bin/cp onestop/blog/models.py $DEPLOYPATH/blog/models.py
    - /bin/cp onestop/blog/urls.py $DEPLOYPATH/blog/urls.py
    - /bin/cp onestop/blog/views.py $DEPLOYPATH/blog/views.py
    # Dictionary
    - /bin/cp -R onestop/dictionary/static/ $DEPLOYPATH/dictionary/
    - /bin/cp -R onestop/dictionary/templates/ $DEPLOYPATH/dictionary/
    - /bin/cp -R onestop/dictionary/tests/ $DEPLOYPATH/dictionary/
    - /bin/cp onestop/dictionary/admin.py $DEPLOYPATH/dictionary/admin.py
    - /bin/cp onestop/dictionary/classes.py $DEPLOYPATH/dictionary/classes.py
    - /bin/cp onestop/dictionary/forms.py $DEPLOYPATH/dictionary/forms.py
    - /bin/cp onestop/dictionary/models.py $DEPLOYPATH/dictionary/models.py
    - /bin/cp onestop/dictionary/urls.py $DEPLOYPATH/dictionary/urls.py
    - /bin/cp onestop/dictionary/views.py $DEPLOYPATH/dictionary/views.py
    - /bin/cp onestop/manage.py $DEPLOYPATH
    # - /bin/cp test_deploy.txt $DEPLOYPATH/dictionary/
    # - /bin/cp onestop/dictionary/test_deploy2.txt $DEPLOYPATH/dictionary/
    # - /bin/cp <file_name> $DEPLOYPATH                 #Copy specific file to destination from root
    # - /bin/cp /<sub_folder>/<file_name> $DEPLOYPATH   #copy specific file from source sub folder
    # - /bin cp * $DEPLOYPATH                           #copy all from root 
    # - /bin cp /<sub_folder>/* $DEPLOYPATH             #copy all from sub folder root
    # - /bin/cp -r * $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH
    
    #https://github.com/FrancoisGeyser/cPanel-yml/blob/master/.cpanel.yml
    
    