---
deployment:
  tasks:
    - export DEPLOYPATH=/home/oshizdab/onestop/
    - export ONESTOPPATH=/home/oshizdab/onestop/onestop/
    - export BLOGPATH=/home/oshizdab/onestop/blog/
    - export DICTIONARYPATH=/home/oshizdab/onestop/dictionary/
    # Non-app files
    - /bin/cp onestop/manage.py $DEPLOYPATH
    - /bin/cp -v onestop/requirements.txt $DEPLOYPATH
    - /bin/cp -R onestop/static/ $DEPLOYPATH
    - /bin/cp -R onestop/templates/ $DEPLOYPATH
    - /bin/cp onestop/onestop/practice.py $ONESTOPPATH
    - /bin/cp onestop/onestop/urls.py $ONESTOPPATH
    # Blog
    - /bin/cp -R onestop/blog/tests/ $BLOGPATH
    # - /bin/cp -R onestop/blog/static/ $BLOGPATH
    - /bin/cp -R onestop/blog/templates/ $BLOGPATH
    - /bin/cp onestop/blog/*.py $BLOGPATH
    # Dictionary
    # - /bin/cp -R onestop/dictionary/static/ $DICTIONARYPATH
    - /bin/cp -R onestop/dictionary/templates/ $DICTIONARYPATH
    - /bin/cp -R onestop/dictionary/tests/ $DICTIONARYPATH
    - /bin/cp onestop/dictionary/*.py $DICTIONARYPATH
    - /bin/cp onestop/manage.py $DEPLOYPATH
    
    