---
deployment:
  tasks:
    - export DEPLOYPATH=/home/oshizdab/onestop/
    - export ONESTOPPATH=/home/oshizdab/onestop/onestop/
    - export BLOGPATH=/home/oshizdab/onestop/blog/
    - export DICTIONARYPATH=/home/oshizdab/onestop/dictionary/
    - export USERSPATH=/home/oshizdab/onestop/users/
    - export EQUEUEPATH=/home/oshizdab/onestop/equeue/
    - export STOREPATH=/home/oshizdab/onestop/store/
    #R for recursive copying, -u for updating (only copies when source is newer than destination)
    # Non-app files
    - /bin/cp -u onestop/manage.py $DEPLOYPATH
    - /bin/cp -u onestop/autodict.py $DEPLOYPATH
    - /bin/cp -u onestop/auto_updater.py $DEPLOYPATH
    - /bin/cp -u onestop/requirements.txt $DEPLOYPATH
    - /bin/cp -Ru onestop/static/ $DEPLOYPATH
    - /bin/cp -Ru onestop/templates/ $DEPLOYPATH
    - /bin/cp -u onestop/onestop/practice.py $ONESTOPPATH
    - /bin/cp -u onestop/onestop/urls.py $ONESTOPPATH
    # Blog
    # - /bin/cp -Ru onestop/blog/static/ $BLOGPATH
    - /bin/cp -Ru onestop/blog/tests/ $BLOGPATH
    - /bin/cp -Ru onestop/blog/templates/ $BLOGPATH
    - /bin/cp -u onestop/blog/*.py $BLOGPATH
    # Dictionary
    # - /bin/cp -Ru onestop/dictionary/static/ $DICTIONARYPATH
    - /bin/cp -Ru onestop/dictionary/templates/ $DICTIONARYPATH
    - /bin/cp -Ru onestop/dictionary/tests/ $DICTIONARYPATH
    - /bin/cp -u onestop/dictionary/*.py $DICTIONARYPATH
    # - /bin/cp -u onestop/manage.py $DEPLOYPATH
    # Users
    - /bin/cp -Ru onestop/users/templates/ $USERSPATH
    - /bin/cp -Ru onestop/users/tests/ $USERSPATH
    - /bin/cp -u onestop/users/*.py $USERSPATH
    # Equeue
    - /bin/cp -Ru onestop/equeue/templates/ $EQUEUEPATH
    - /bin/cp -Ru onestop/equeue/templatetags/ $EQUEUEPATH
    - /bin/cp -Ru onestop/equeue/tests/ $EQUEUEPATH
    - /bin/cp -u onestop/equeue/*.py $EQUEUEPATH
    # Store
    - /bin/cp -Ru onestop/store/templates/ $STOREPATH
    - /bin/cp -Ru onestop/store/tests/ $STOREPATH
    - /bin/cp -u onestop/store/*.py $STOREPATH
    # To do manually: edit settings, collectstatic (before commit in dev??), run migrations
    
    